from typing import Protocol

from aipe_devices.domain.device import PowerSemiconductorDevice


class DeviceRepository(Protocol):
    def get(self, device_id: str) -> PowerSemiconductorDevice: ...
    def list(self) -> tuple[str, ...]: ...
    def search(self, query: str) -> tuple[PowerSemiconductorDevice, ...]: ...
    def save(self, device: PowerSemiconductorDevice) -> None: ...
    def update(self, device: PowerSemiconductorDevice, *, expected_revision: int) -> None: ...
